### ISSUE TITLE
Suggestion: macro encode-object-slots

### ISSUE THREAD

**Issue by fiveop** [hanshuebner/yason#28]
I use the following macro in my projects to implement `ENCODE-SLOTS`. If you deem it useful in general, I would write a patch with documentation.

    (defmacro encode-object-slots (object slots)
      `(with-slots ,slots ,object
         (yason:encode-object-elements
          ,@(loop :for slot :in slots
               :append `(',slot ,slot)))))

**Comment by tmccombs** [comment]
As written it has to be a macro, since with-slots is a macro, and needs to know the slot names at compile time. However it could be written as a function like this:

```lisp
(defun encode-object-slots (object slots)
  (encode-object-elements
    (loop for slot in slots
        collect slot
        collect (slot-value object slot))))
```

**Comment by hanshuebner** [comment]
The function does indeed look useful to me, do you want to submit a PR?

2015-05-17 6:45 GMT+02:00 Thayne McCombs <notifications@github.com>:
