### ISSUE TITLE
Proposal: a safe predicate for JSON booleans

### ISSUE THREAD

**Issue by gschjetne** [hanshuebner/yason#30]
Here's a snippet of code I've been using to check whether something is true or not, regardless of whether null and the booleans are parsed as symbols or not:

```lisp
(defun true-p (yason-bool)
  (case yason-bool
    ('yason:false nil)
    (:null nil)
    (otherwise yason-bool)))
```

It's especially helpful when writing libraries using YASON where you don't want to make assumptions about what the user might have bound `*parse-json-booleans-as-symbols*` and `*parse-json-null-as-keyword*` but still need to reliably check truth values.

The question, before I go ahead and make a patch out of it, is how strictly it should adhere to what is true and false in JavaScript. In JavaScript the number 0 and the empty string is also false, which is just two more clauses in the case expression, but empty array in JavaScript is true, so is empty array in Lisp, but that conflicts with parsing arrays as lists, or bools as `t`/`nil`.

I would prefer to keep it as it stands, lispers are already used to using `zerop` and checking sequence lengths, and the latter is probably too much of a fringe case to be worth the trouble.

**Comment by hanshuebner** [comment]
I'm not sure I understand what this predicate is meant to be used for.  I
wonder whether it would not be better if a library that uses YASON properly
configures it rather than making any guesses about its parse outcome.
Also, I don't think that JavaScript semantics are applicable in this
context, but I might be wrong.  Can you try to explain a use case?

2015-01-08 13:36 GMT+01:00 Grim Schjetne <notifications@github.com>:

**Comment by gschjetne** [comment]
My current use case is a library for interfacing with Elasticsearch. I could of course as you said hard-code the behaviour to ensure the data always survives the round-trip, but that would require users to always check the symbols, even if they don't care about preserving JavaScript semantics. A compromise could be to assume the former is what they want, and have a special variable to override it with.

**Comment by hanshuebner** [comment]
I still don't understand, bear with me:  You are worried that a user of
your library might also use YASON and configure it in a way that breaks
your library?  Or something else?

2015-01-12 11:05 GMT+01:00 Grim Schjetne <notifications@github.com>:

**Comment by gschjetne** [comment]
The Elastic library parses JSON coming from the database. The user may want this parsed either as symbols or `t` and `nil` depending on the specifics of their own application. This is a way of passing the choice transparently on to the user.

It may also be of use to others who uses the symbols for any other purpose, which is why I'm making the suggestion. Otherwise I'll just keep it in my own library.

**Comment by hanshuebner** [comment]
Given that it seems to be hard to explain precisely what is going on and
how, I'll prefer if you keep the function in your own library.  I would
suggest that you do not open up YASON configuration as a means to configure
your Elasticsearch library.

2015-01-12 14:15 GMT+01:00 Grim Schjetne <notifications@github.com>:

**Comment by gschjetne** [comment]
The complete opposite effect is achieved. No configuration change to YASON alters the behaviour of my library, giving the user more control and making the library more robust.

Precisely what's going on is trivial:
```lisp
(true-p (parse "false") => nil
(true-p (parse "null") => nil
```
regardless of the configuration.

The general use case is whenever someone wants to use the symbols option, but still want to use the values in conditionals without the wrong part evaluating. I do it all the time, and if it's useful for anyone else, by all means, take it, otherwise, don't.

**Comment by hanshuebner** [comment]
Well, either I'm dumb or you are failing to explain what you're trying to
get into YASON.  Let me put it this way:  If you cannot describe how the
function that you want to add would be used, then I don't want it.  I'm
probably dumber than I would like to admit, but I like to believe that I am
not the dumbest person on earth, so for the sake of the users of YASON, let
us assume that I need to understand it.

Maybe you could start freshly and come up with a 4 sentence description of
what your function does and how it would be used by another YASON user.

-Hans

2015-01-12 17:30 GMT+01:00 Grim Schjetne <notifications@github.com>:

**Comment by gschjetne** [comment]
It's really no more useful than a way for letting lazy programmers such as myself check that the value they're dealing with is neither `yason:false` nor `yason:true`. There's no real downside to having people define such a function themselves. I would go on for two more sentences, but there's a risk it would just turn into a gross exaggeration of the merits of the idea. :)
