### ISSUE TITLE
Encoding objects where the value is an array or object

### ISSUE THREAD

**Issue by eudoxia0** [hanshuebner/yason#31]
Consider:

```lisp
CL-USER> (yason:with-output (*standard-output*)
           (yason:with-object ()
             (yason:encode-object-elements
              "name" "Ingmar Bergman"
              "movies" (yason:with-array ()
                         (yason:encode-array-elements
                          "The Seventh Seal" "Persona" "The Silence")))))
{["The Seventh Seal","Persona","The Silence"],"name":"Ingmar Bergman","movies":null}
```

Here, the array is written to the stream out of place, presumably because the call to `with-array` is being evaluated before `encode-object-elements` has time to do its thing.

What should I do here to encode this kind of objects, other than turn them into an alist and call `encode` on that?

**Comment by hanshuebner** [comment]
You need to use `with-object-element`.  The manual has an example here:
https://common-lisp.net/projects/yason/#stream-encoder


2015-02-05 14:47 GMT-05:00 Fernando Borretti <notifications@github.com>:

**Comment by eudoxia0** [comment]
I can't believe I missed that. I saw the example but kept misreading `with-object-element` as `encode-object-element`.
