### ISSUE TITLE
Continuing difficulties with encode-alist

### ISSUE THREAD

**Issue by dfmorrison** [hanshuebner/yason#35]
This is with yason 0.7.6 under CCL:

    ? (format t "~@{~A~%~}"
            (asdf:component-version (asdf:find-system :yason))
            (lisp-implementation-type)
            (lisp-implementation-version)
            (software-type)
            (software-version)
            (machine-type)
            (machine-version))
    0.7.6
    Clozure Common Lisp
    Version 1.10-r16196  (LinuxX8664)
    Linux
    3.16.0-50-generic
    x86_64
    Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
    NIL

When representing a JSON object as an a-list there is ambiguity if JSON arrays are lists, or `nil` is used for JSON `false` or `null`. For example, both `[["a", "b"]]` and `{"a":["b"]}` parse as the same S-expression `(("a" "b"))`. However, while there is not a unique encoding of such an S-expression, I wouldn't expect it to simply give up this way, particularly since it has emitted a partial encoding:

    ? (load (merge-pathnames "test.lisp" (asdf:system-source-directory :yason)))
    #P"/home/dfm/common-lisp/yason/test.lisp"

    ? yason-test::*basic-test-json-string* 
    "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"

    ? (yason:parse yason-test::*basic-test-json-string* :object-as :alist)
    ((("bar" 7 8 9) ("foo" . 1)) 2 3 4 (5 6 7) T NIL)

    ? (yason:encode-alist *)
    {
    > Error: The value ("bar" 7 8 9) is not of the expected type (OR STRING SYMBOL CHARACTER).
    > While executing: STRING, in process listener(1).
    > Type :POP to abort, :R for a list of available restarts.
    > Type :? for other options.
    1 > :pop

Even worse, though, is that if we parse JSON arrays as Lisp vectors, and use symbols/keywords for JSON `true`, `false` and `null` we *should* have a clean, bijective mapping between JSON and Lisp, apart from floating point number issues. And yet even in this case yason is signalling an error, again after emitting a partial encoding:

    ? (yason:parse yason-test::*basic-test-json-string*
                 :object-as :alist
                 :json-arrays-as-vectors t
                 :json-booleans-as-symbols t
                 :json-nulls-as-keyword t)
    #((("bar" . #(7 8 9)) ("foo" . 1)) 2 3 4 #(5 6 7) YASON:TRUE :NULL)

    ? (yason:encode-alist *)
    {
    > Error: The value #<VECTOR 20 fill-pointer 7, adjustable> is not of the expected type LIST.
    > While executing: YASON:ENCODE-ALIST, in process listener(1).
    > Type :POP to abort, :R for a list of available restarts.
    > Type :? for other options.
    1 >

**Comment by dfmorrison** [comment]
Upgrading CCL from 1.10 to 1.11 does not fix this problem, but it does change the error message:

```
? (asdf:component-version (asdf:find-system :yason))
"0.7.6"
? (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"   :object-as :alist)
((("foo" . 1) ("bar" 7 8 9)) 2 3 4 (5 6 7) T NIL)
? (yason:encode-alist *)
[[["foo"
> Error: The value 1 is not of the expected type LIST.
> While executing: YASON::ENCODE-LIST%, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

and

```
? (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"
             :object-as :alist
             :json-arrays-as-vectors t
             :json-booleans-as-symbols t
             :json-nulls-as-keyword t)
#((("foo" . 1) ("bar" . #(7 8 9))) 2 3 4 #(5 6 7) YASON:TRUE :NULL)
? (yason:encode-alist *)
[[["foo"
> Error: The value 1 is not of the expected type LIST.
> While executing: YASON::ENCODE-LIST%, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

**Comment by dfmorrison** [comment]
These two examples also fail in SBCL (1.2.11):

```
* (asdf:component-version (asdf:find-system :yason))

"0.7.6"
* (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"   :object-as :alist)

((("bar" 7 8 9) ("foo" . 1)) 2 3 4 (5 6 7) T NIL)
* (yason:encode-alist *)
{
debugger invoked on a SIMPLE-TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1002D86653}>:
  ("bar" 7 8 9) is not a string designator.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(STRING ("bar" 7 8 9))
0] 
* (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"
             :object-as :alist
             :json-arrays-as-vectors t
             :json-booleans-as-symbols t
             :json-nulls-as-keyword t)

#((("bar" . #(7 8 9)) ("foo" . 1)) 2 3 4 #(5 6 7) YASON:TRUE :NULL)
* (yason:encode-alist *)
{
debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1002D86653}>:
  The value #((("bar" . #(7 8 9)) ("foo" . 1)) 2 3 4 #(5 6 7) YASON:TRUE :NULL)
  is not of type
    LIST.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(YASON:ENCODE-ALIST #((("bar" . #(7 8 9)) ("foo" . 1)) 2 3 4 #(5 6 7) YASON:TRUE :NULL) #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10001CB7A3}>)
0] 
```

**Comment by hanshuebner** [comment]
I understand that you're struggling with the fact that JSON datatypes are not Lisp datatypes.  YASON recognises that mismatch and supports the streaming encoder interface to make it possible to create whatever JSON representation is required.  A perfect bijective mapping between JSON and some arbitrary Lisp data structure was not a design goal of YASON, and I'm reluctant to include another change that heuristically determines the "right thing" given some nested Lisp data structure when encoding.

**Comment by dfmorrison** [comment]
I'm sorry I didn't make myself clear. I'm not thinking that any Lisp S-expression should be representable as JSON. What I do think, though, is that if yason is presented with a JSON structure X, and on parsing it, a Lisp structure Y is created, then I would expect yason to be able to take Y back to a JSON structure. Ideally back to X, but I understand that for some settings that may not be possible; but blowing up completely seems very odd.

I'm not sure, but I think that there is *no* S-expression that `encode-alist` will encode as, say

```
{"foo":1,"bar":[7,8,9]},2,3,4,[5,6,7],true,null]
```

If indeed there is no way to produce this result, short of doing it by hand by walking the structure myself and making a bunch of carefully constructed calls to things like `encode-array-element` and `encode-object-element` it seems like a rather sad omission.

**Comment by hanshuebner** [comment]
Because Lisp datatypes and JSON datatypes are incompatible, YASON provides a way to produce arbitrary JSON through its streaming encoding interface.  That is a design choice, not an omission.  I am opposed to including heuristics in the standard API that cause unpredictable behavior like described in this original bug report.

If you require a non-streaming interface to serialize a certain nested Lisp data structure as JSON, it would be best if you'd just write an encoding function for that kind of structure in your application layer.  The reason why I am opposed to making such an encoder interface be part of the standard YASON API is that such an interface is bound to break if presented a slightly different data structure or used with modified encoder settings.

Please have a look at the documentation again:  It clearly states that YASON does not impose a particular object model on the application.  It was my mistake to have left that route by including the functionality that I have now removed again.
