### ISSUE TITLE
WITH-OUTPUT-TO-STRING* is exported, but doesn't have an external stream symbol

### ISSUE THREAD

**Issue by fiddlerwoaroof** [hanshuebner/yason#43]
The macro WITH-OUTPUT-TO-STRING* binds the json-stream to YASON::S and doesn't take an argument to provide another symbol.  Is this intended behavior, or a mistake in the macro?

https://github.com/hanshuebner/yason/blob/1779dbe8cd1e09060e6571a79b011a5b7eb759f2/encode.lisp#L209-L215

**Comment by hanshuebner** [comment]
This looks like a mistake in the macro.
